services:
 db:
  image: mysql:8.0.40
  container_name: mysql-docker
  environment:
   MYSQL_ROOT_PASSWORD: root
  ports:
   - "3306:3306"
  volumes:
   - devdojo_maratona_data:/var/lib/mysql

volumes:
 devdojo_maratona_data:

#Comandos

# docker-compose up: executa o arquivo .yml e faz download da imagem
# docker-compose down: remove a imagem mas não os volume (verificar a documentação)
# docker-compose stop: para a execução do container
# docker ps: verificar quais containers estão sendo executados
# CTRL+C: finalizar o container via terminal
# docker ps -a: verifica todos as imagens
# docker volume ls: verifica os volumes criados